### ISSUE TITLE
Design decision: Pass executionClaimOwner as parameter or fetch from state

### ISSUE THREAD

**Issue by hilmarx** [gelatodigital/gelato#142]

**Comment by hilmarx** [comment]
**Fetching Execution Claim Owner from state:**

- allows users to mint tokens with one wallet and then transfer the token to another one. Example sell on dutchX with one wallet and get the tokens withdrawn to another one.
- This however does not work for most use cases, as the approve to sell is only conducted at minting time, hence if a user mints a claim to sell 10WETH for DAI and transfers it to another address, this address will not have set the approval to get its funds withdrawn. This would, however, work if we use actions that apply create2. This would also enable future like contracts, where user A transfers 100DAi in create2 contract, mints gelato token, transfers gelato Token to user B, who then receives the output of the action of the create2 contract after it is executed. => However, stick to approve / mint flow for this poc

**Verdict:** It doesn't really make sense to fetch the execution Claim from state for this poc as long as we are not working with create2 and a proxy contract which allows the actions to move its funds automatically.

**Comment by hilmarx** [comment]
=> As long as the funds are not moved out of the users wallet at minting time, trading the underlying erc721 makes no sense. Let's hide that feature and add it for later iterations.

**Comment by hilmarx** [comment]
=>=> We'll channel the executionClaimOwner via callData, not state.

**Comment by gitpusha** [comment]
Luis edits (commit 94ae360) 
----
**MAJOR UPDATE: _We fetch the executionClaimOwner from gelatoCore state in the actions_**

This makes sense because 

- GelatoExecutionClaim ERC721 transferability now is functional with all the great use cases that are enabled by it

- The problem of `approve` funds regarding the `transfer` of the `GTA token`  can also be handled in the frontend (or maybe in smart contracts): our `users` use a `UI` to begin with. They will not try to interact with Ethereum in other ways - therefore, `we can build` the `UI` for our  `token transfers` and `handle the approve funds before transfer` in the `frontend` -- alternatively we can build such `approval and transfer` flows into the `smart contracts`.

**Comment by hilmarx** [comment]
> GelatoExecutionClaim ERC721 transferability now is functional with all the great use cases that are enabled by it

As long as we dont transfer some funds at minting time, which we don't at the moment, I don't see any great use cases. In order to withdraw tokens or eth upfront, we would have to redesign the aggregator again, because doing so will make it significantly harder to write the aggregator contract as generalistic as it is now. 

Whether or not the executionClaimOwner is read from state is subject to the action anyways. And because we have to redeploy the actions in case we want to use create2 (assumption), I would say we might as well save gas and pass executionClaimOwner as calldata for now.

**Comment by hilmarx** [comment]
Update, we fetch executionClaimOwner from the proxy by calling ```Owner```
