### ISSUE TITLE
Final edits: executor whitelist

### ISSUE THREAD

**Issue by gitpusha** [gelatodigital/gelato#83]

**Comment by gitpusha** [comment]
@hilmarx need to rediscuss this

**Comment by hilmarx** [comment]
no whitelist, everyone can be an executor. We permission on the interface level

**Comment by gitpusha** [comment]
@hilmarx 
ok - I will introduce an `executor whitelist` into the `IcedOut` standard

**Comment by hilmarx** [comment]
1. My first feeling is to keep that core as clean and open as possible and only restrict further out, i.e. in the triggers
2. I would in general only restrict triggers, otherwise, the trigger will return true, executors execute and get a reverted tx with gas cost losses, which is bad for other people running nodes
3. We can e.g. deploy each action contract twice, one permissionless and one with an executor whitelist, that conducts the ```tx.origin``` check you mentioned above.

**Comment by gitpusha** [comment]
Answer:
ExecutionClaimOwner wird vom GTAI gepassed und mit in executionClaim gehashed

Backup in case of stackTooDeep -> check on trigger
